### ISSUE TITLE
[MELHORIA]Objetivo Estratégico, Meta, Diretriz Estratégica

### ISSUE THREAD

**Issue by rafaeljcg20** [culturagovbr/siminc2#1049]
Realizar as seguintes atividades relacionadas:
- [x] Desenvolver nova tela de Apoio Objetivos do Planejamento Estratégico com a possibilidade de administrar(Inserir, Alterar, Listar e excluir) Metas e Diretrizes;
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/1ea20bf6-18e7-4634-a4e5-b85b1ea314b4)

- [x] Desenvolver nova tela de Configuração -> Vincular Metas do Planejamento Estratégico;
![image.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/68deb1c6-cae2-4a63-956a-97abcdca3710)

- [x] Inserir opções de Objetivo Estratégico, Meta e Diretriz na tela de Cadastro de PI. Obs: Pra todos os tipos de enquadramentos;
![screenshot-siminc2.cultura.gov.br-2019.03.25-11-42-15.png](https://images.zenhubusercontent.com/5a9feb394b5806bc2bc9ca9f/8da4f8c5-3b92-40db-a87a-0448f43fee5f)

- [x] Inserir as novas informações de  Objetivo Estratégico, Meta e Diretriz no relatório Geral.

**Comment by dougs007** [comment]
Nome da branch:

hotfix-1049-planejamento-objetivo-meta-diretriz

**Comment by dougs007** [comment]
- [ ] Script para OTRS.




-- DROP SEQUENCE planacomorc.objetivo_estrategico_obeid_seq;
CREATE SEQUENCE planacomorc.objetivo_estrategico_obeid_seq
INCREMENT 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 1
CACHE 1;
ALTER TABLE planacomorc.objetivo_estrategico_obeid_seq
OWNER TO postgres;
GRANT ALL ON SEQUENCE planacomorc.objetivo_estrategico_obeid_seq TO postgres;
GRANT SELECT, USAGE ON SEQUENCE planacomorc.objetivo_estrategico_obeid_seq TO usr_simec;

-- DROP TABLE planacomorc.objetivo_estrategico;
CREATE TABLE planacomorc.objetivo_estrategico(
obeid integer NOT NULL DEFAULT nextval('planacomorc.objetivo_estrategico_obeid_seq'::regclass), -- Chave Primária
obecod character varying(4),
obenome character varying(125),
obecadastro timestamp without time zone NOT NULL DEFAULT now(),
prsano character(4) NOT NULL,
obestatus character(1) NOT NULL DEFAULT 'A'::bpchar, -- Status: ...
CONSTRAINT pk_objetivo_estrategico_obeid PRIMARY KEY (obeid),
CONSTRAINT fk_programacao_exercicio_prsano FOREIGN KEY (prsano)
REFERENCES planacomorc.programacaoexercicio (prsano) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION)
WITH (OIDS=FALSE);
ALTER TABLE planacomorc.objetivo_estrategico
OWNER TO postgres;
GRANT ALL ON TABLE planacomorc.objetivo_estrategico TO postgres;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE planacomorc.objetivo_estrategico TO usr_simec;
COMMENT ON COLUMN planacomorc.objetivo_estrategico.obeid IS 'Chave Primária';
COMMENT ON COLUMN planacomorc.objetivo_estrategico.obecod IS 'Código do Objetivo Estratégico';
COMMENT ON COLUMN planacomorc.objetivo_estrategico.obenome IS 'Nome do Objetivo Estratégico';
COMMENT ON COLUMN planacomorc.objetivo_estrategico.obecadastro IS 'Data de cadastro do registro';
COMMENT ON COLUMN planacomorc.objetivo_estrategico.prsano IS 'Exercício do ano corrido do registro';

-- DROP SEQUENCE planacomorc.meta_estrategica_meeid_seq;
CREATE SEQUENCE planacomorc.meta_estrategica_meeid_seq
INCREMENT 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 1
CACHE 1;
ALTER TABLE planacomorc.meta_estrategica_meeid_seq
OWNER TO postgres;
GRANT ALL ON SEQUENCE planacomorc.meta_estrategica_meeid_seq TO postgres;
GRANT SELECT, USAGE ON SEQUENCE planacomorc.meta_estrategica_meeid_seq TO usr_simec;

-- DROP TABLE planacomorc.meta_estrategica;
CREATE TABLE planacomorc.meta_estrategica(
meeid integer NOT NULL DEFAULT nextval('planacomorc.meta_estrategica_meeid_seq'::regclass), -- Chave Primária
meecod character varying(4),
meenome character varying(125),
meecadastro timestamp without time zone NOT NULL DEFAULT now(),
prsano character(4) NOT NULL,
meestatus character(1) NOT NULL DEFAULT 'A'::bpchar, -- Status: ...
obeid integer NOT NULL,
CONSTRAINT fk_programacao_exercicio_prsano FOREIGN KEY (prsano)
REFERENCES planacomorc.programacaoexercicio (prsano) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION,
CONSTRAINT fk_objetivo_estrategico_obeid FOREIGN KEY (obeid)
REFERENCES planacomorc.objetivo_estrategico (obeid) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION)
WITH (OIDS=FALSE);
ALTER TABLE planacomorc.meta_estrategica
OWNER TO postgres;
GRANT ALL ON TABLE planacomorc.meta_estrategica TO postgres;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE planacomorc.meta_estrategica TO usr_simec;
COMMENT ON COLUMN planacomorc.meta_estrategica.meeid IS 'Chave Primária';
COMMENT ON COLUMN planacomorc.meta_estrategica.meecod IS 'Código da Meta Estratégica';
COMMENT ON COLUMN planacomorc.meta_estrategica.meenome IS 'Nome da Meta Estratégica';
COMMENT ON COLUMN planacomorc.meta_estrategica.meecadastro IS 'Data de cadastro do registro';
COMMENT ON COLUMN planacomorc.meta_estrategica.prsano IS 'Exercício do ano corrido do registro';
COMMENT ON COLUMN planacomorc.meta_estrategica.obeid IS 'Chave Estrangeira de Objetivo Estratégico';





-- DROP SEQUENCE planacomorc.diretriz_estrategica_dieid_seq;
CREATE SEQUENCE planacomorc.diretriz_estrategica_dieid_seq
INCREMENT 1
MINVALUE 1
MAXVALUE 9223372036854775807
START 1
CACHE 1;
ALTER TABLE planacomorc.diretriz_estrategica_dieid_seq
OWNER TO postgres;
GRANT ALL ON SEQUENCE planacomorc.diretriz_estrategica_dieid_seq TO postgres;
GRANT SELECT, USAGE ON SEQUENCE planacomorc.diretriz_estrategica_dieid_seq TO usr_simec;

-- DROP TABLE planacomorc.diretriz_estrategica;
CREATE TABLE planacomorc.diretriz_estrategica(
dieid integer NOT NULL DEFAULT nextval('planacomorc.diretriz_estrategica_dieid_seq'::regclass), -- Chave Primária
diecod character varying(4),
dienome character varying(125),
diecadastro timestamp without time zone NOT NULL DEFAULT now(),
prsano character(4) NOT NULL,
diestatus character(1) NOT NULL DEFAULT 'A'::bpchar, -- Status: ...
obeid integer NOT NULL,
CONSTRAINT pk_diretrizes_estrategicas_dieid PRIMARY KEY (dieid),
CONSTRAINT fk_programacao_exercicio_prsano FOREIGN KEY (prsano)
REFERENCES planacomorc.programacaoexercicio (prsano) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION,
CONSTRAINT fk_objetivo_estrategico_obeid FOREIGN KEY (obeid)
REFERENCES planacomorc.objetivo_estrategico (obeid) MATCH SIMPLE
ON UPDATE NO ACTION ON DELETE NO ACTION)
WITH (OIDS=FALSE);
ALTER TABLE planacomorc.diretriz_estrategica
OWNER TO postgres;
GRANT ALL ON TABLE planacomorc.diretriz_estrategica TO postgres;
GRANT SELECT, UPDATE, INSERT, DELETE ON TABLE planacomorc.diretriz_estrategica TO usr_simec;
COMMENT ON COLUMN planacomorc.diretriz_estrategica.dieid IS 'Chave Primária';
COMMENT ON COLUMN planacomorc.diretriz_estrategica.diecod IS 'Código da Diretriz Estratégica';
COMMENT ON COLUMN planacomorc.diretriz_estrategica.dienome IS 'Nome do Diretriz Estratégica';
COMMENT ON COLUMN planacomorc.diretriz_estrategica.diecadastro IS 'Data de cadastro do registro';
COMMENT ON COLUMN planacomorc.diretriz_estrategica.prsano IS 'Exercício do ano corrido do registro';

**Comment by rafaeljcg20** [comment]
Foi realizada uma publicação parcial para poder ser feito o preenchimento dos objetivos, metas e diretrizes do Planejamento Estratégico.

**Comment by dougs007** [comment]
Testado em homologação:

http://homologasiminc2.cultura.gov.br/planacomorc/planacomorc.php?modulo=relatorio/geral&acao=A

**Comment by rafaeljcg20** [comment]
Correções na tela de Cadastro de PAs:
- [ ] Verificar se as regras de exibição de Metas estão sendo corretamente aplicadas a exibição da nova opção Metas do Planejamento estratégico. Eg: Se está sendo filtrado as metas conforme a Subuinidade selecionada e se está exibindo também as metas não vinculadas as Subunidades;

Correções na tela de Cadastro de Objetivos:
- [ ] Aumentar quantidade mínima de caracteres do título de todos os formulários(Objetivo, Meta, diretriz);
- [ ] Fazer com que quando a tecla [ENTER] for acionado o sistema salve autmaticamente os dados do formulário(Perguntar e tirar dúvidas a respeito disso, antes da implementação);
- [ ] Inserir o botão de Novo e botão de Cancelar(reset) com a finalidade de recarregar o formulário conforme o estado inicial dele;
